# Generated by Django 4.2.4 on 2023-09-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='unknown', max_length=50, verbose_name='страна'),
            preserve_default=False,
        ),
    ]
