# Generated by Django 4.2.4 on 2023-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
    ]
