# Generated by Django 4.2.4 on 2023-08-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(default=None, max_length=150, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
