# Generated by Django 4.2.4 on 2023-08-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата закрытия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение'),
        ),
    ]
