# Generated by Django 4.2.4 on 2023-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='num',
            field=models.IntegerField(default=0, verbose_name='номер версии'),
        ),
    ]
